### ISSUE TITLE
error on getusers

### ISSUE THREAD

**Issue by rfgarnier** [AKouki/SignalR-Chat#13]
we sometimes get this error, any idea?

fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'GetUsers'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Chat.Web.Hubs.ChatHub.<>c__DisplayClass8_0.<GetUsers>b__0(UserViewModel u) in C\Hubs\ChatHub.cs:line 89
         at System.Linq.Enumerable.WhereListIterator`1.ToList()
         at lambda_method22(Closure , Object , Object[] )
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass16_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()

**Comment by AKouki** [comment]
Can you provide more details about when it happens?

Please logout from all accounts, clear cookies and let me know if that helps.

It seems that somehow you have null user objects in _Connections list.

**Comment by meistvan** [comment]
Is your 'project' designed to basically work within Visual Studio?
If not, and can be 'deployed' externally, could you provide the steps necessary?

Thanks

**Comment by AKouki** [comment]
The project is mainly created for inspiration. As an example application.

If you want to deploy this you will propably want a database and a storage solution for uploaded images.
